# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Article',
        ),
    ]
